spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      schema-locations: classpath*:table/h2/schema.sql
      data-locations: classpath*:table/h2/data.sql
      mode: always
      encoding: utf-8
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  profiles:
    include: oauth, google

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

scheduler:
  test:
    cron: "0 0/1 * * * ?"
  cron: "0 */5 * * * *"
  weather:
    cron: "0 * 6 * * ?"
