# aws 설정
# S3 bucket region
#key
cloud:
  aws:
    credentials:
      access-key: "AKIATHXM74KRW72HGAJM"
      secret-key: "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"
    region:
      static: "ap-south-1"
    stack:
      auto: false