spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "899822161186-u1mgp3jjrsnimb5ulv0ro79ksnkb6g6v.apps.googleusercontent.com"
            client-secret: "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"
            scope: profile, email
            redirect-uri: "http://ec2-13-127-154-248.ap-south-1.compute.amazonaws.com:8080/login/oauth2/code/google"
#            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

  datasource:
    #    url: jdbc:mysql://localhost:3306/chalkak?serverTimezone=UTC&charsetEncoding=UTF-8
    url: jdbc:h2:mem:chalkak;DB_CLOSE_DELAY=-1
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
    #    username: root
    #    password: 1234
    username: sa
    password:

  # redis
  redis:
    host: 127.0.0.1
    port: 6379
  # jwt
  jwt:
    secret: UmVjb21tZW5kYXRpb24gU2VydmljZSBDaGFsa2FrIEJ5IFplcm9CYXNlIEJhY2tlbmQgU2Nob29sIDExIA==

openWeather:
  key: "b6984cc1cea8abd964d364969316e0af"

